
services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - src/main/resources/env/db-config.env
    ports:
      - "5432:5432"
  web:
    depends_on:
      - db
    image: openjdk:17-jdk-alpine
    env_file:
      - src/main/resources/env/db-config.env
    ports:
      - "8080:8080"
    restart: always
