version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - db-config.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: 5432
    expose:
      - 5432
  web:
    depends_on:
      - db
    image: zoode-backend
    env_file:
      - db-config.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_TITLE: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
