version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - src/main/resources/env/db-config.env
    ports:
      - "5432:5432"
    container_name:
      zoode-db
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/main/resources/env/.env
    ports:
      - "7890:7879"
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/zoode-db
      - SPRING_DATASOURCE_USERNAME=defaultuser
      - SPRING_DATASOURCE_PASSWORD=defaultpassword
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - src/main/resources/env/.env
    volumes:
      - minio_storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_storage: {}