version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: defaultpassword
      POSTGRES_USER: defaultuser
      POSTGRES_DB: zoode-db
      PGPORT: 5432
    expose:
      - 5432
  web:
    depends_on:
      - db
    image: zoode-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_TITLE: zoode-db
      DB_PASSWORD: defaultpassword
    ports:
      - 8080:8080
    restart: always
